name: Deploy Flutter Web ke GitHub Pages

on:
  push:
    branches:
      - main # Ganti ke 'master' jika branch utamamu bernama master

# Memberikan izin agar action bisa mem-publish ke branch gh-pages
permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build -d

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/send_z/"

      - name: Deploy ke GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web